[workspace]

members = [
    "jaya-ecs",
    "jaya-test",
    # "mvec"
]

[workspace.dependencies]
derive_more = "0.99.17"
delegate = "0.9.0"

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 3